title: Hello, world! I'm Gokul Prasad
description: > # this means to ignore newlines until "baseurl:"
  stuffs & things !
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gokul Prasad # add your name
author-img: logo.png # add your photo
about-author: Ordinary Life! Ordinary Thoughts! # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: gokulprasadthekkel # add your Github handle
social-linkedin: gokul-prasad-429439136 # add your Linkedin handle
social-email: gokulprasadthekkel@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
