title: Hello, world! I'm Gokul Prasad
description: > # this means to ignore newlines until "baseurl:"
  stuffs & things !
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Schrödinger's Cat # add your name
author-img: logo.png # add your photo
about-author: Dead and Alive! # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: gokulprasadthekkel # add your Github handle
social-linkedin: gokul-prasad-429439136 # add your Linkedin handle
social-email: gokulprasadthekkel@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

staticman_url: https://staticman-gptbot.herokuapp.com/v2/entry/gokulprasadthekkel/gokulprasadthekkel.github.io/master/comments

reCaptcha:
  siteKey: 6Lcrk7wZAAAAAIhNFwVyYU54eX4LG_x3mpCW0qw3
  secret: ICCP0XzgMb09kR0sAm5ZsYuWe82+nQrYzeWMzdRjpE+UfjegwSdrOxebqpGFoS435GpZxmsP4u16SxZGdtvylbneZsVWPPxEWQJqXr144/IW7IvTXAJtvJ/L0v6iepRee2lAz+8q0Tfwnxde9eJGSglu+eyUQ/wkMSQbdpLt5pbswyL1UK/h2ZtnUO2jbakv2IGIj3UBH+bp6AT2aC+rew0+v9heNxUiZYdpG7Q7NDlU1M94FGK6JvuKLtXrnsvjbGqy6O/mwST5PYQk3qNWVAVpexPtZO1Qvpp72V3a9Z1Yuuzsv5OsE/xHOyhOOwzMyGQGIZJTPR8csA5jV6TpmR7BUME1q0vLnN5tA5ChWQ3UUYJRsIwkbi4kZRTmCmaiJTheaKMfIgHuG6hBzeiJF0DOEaSY3ZpCT0LoIEBdH+2uwDa/OsIkK+vRSlF7YnF1dplisoUJUjb22/lQharRQle50M+gcjFtjnhbo+Zsu/VVw+eBaam6+APxjEr24aV1FbIJVy2FDtZUC+ur4rJHEu/IzRA3QlSWwWHbq6iaVuutYMiY32XjvM+dHA5VnH1Z7/+hCRJmtusXePjbZOjFNgJZyfsK0beZMi3t0jZHTMiAsnbqeKQ6iyMJy98oNklVnH6tb4o+i8vBHvv29/6MMyyqtjggbWHO6xeZzzbwH+E=
